# Generated by Django 3.2.2 on 2023-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnkaraClothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('men', 'men'), ('female', 'female'), ('all', 'all')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('age_bracket', models.CharField(choices=[('all', 'all'), ('kids', 'kids'), ('teens/adults', 'teens/Adults')], max_length=100)),
                ('descriptions', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(blank=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('previous_price', models.IntegerField()),
                ('slug', models.SlugField(default='offer', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'smartphone ',
            },
        ),
    ]
