# Generated by Django 3.2.2 on 2023-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnkaraClothing', '0002_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='bt_speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(blank=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('previous_price', models.IntegerField()),
                ('slug', models.SlugField(default='product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(blank=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('previous_price', models.IntegerField()),
                ('slug', models.SlugField(default='product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='earphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(blank=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('previous_price', models.IntegerField()),
                ('slug', models.SlugField(default='product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='protector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(blank=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('previous_price', models.IntegerField()),
                ('slug', models.SlugField(default='product', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='smartphone',
            options={},
        ),
        migrations.RemoveField(
            model_name='charger',
            name='age_bracket',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='color',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='age_bracket',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='color',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='gender',
        ),
    ]
